"""empty message

Revision ID: 32639f761495
Revises: 9a4b43c5c344
Create Date: 2023-12-04 18:43:08.365362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32639f761495'
down_revision = '9a4b43c5c344'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_spectra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.create_unique_constraint('unique_user_title', ['user_id', 'title'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_spectra', schema=None) as batch_op:
        batch_op.drop_constraint('unique_user_title', type_='unique')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
