"""empty message

Revision ID: 951acf41feda
Revises: 94fed46be164
Create Date: 2023-12-04 19:11:47.634066

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '951acf41feda'
down_revision = '94fed46be164'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_spectra', schema=None) as batch_op:
        batch_op.drop_index('ix_user_spectra_timestamp')
        batch_op.drop_constraint('unique_user_title', type_='unique')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('title')
        batch_op.drop_column('user_id')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('intensity')
        batch_op.drop_column('frequency')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_spectra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('frequency', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('intensity', sa.BLOB(), nullable=True))
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=64), nullable=True))
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'])
        batch_op.create_unique_constraint('unique_user_title', ['user_id', 'title'])
        batch_op.create_index('ix_user_spectra_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
